// Creed App — Curated Materials Database
// Based on Bernard's real shop list + Home Depot mid-range pricing
// Add HD SKUs as you find them — format: sku?: "305446612"

export interface MaterialItem {
  name: string;
  price: number;
  category: string;
  sku?: string;
  keywords: string[]; // for matching from inspection text
}

export const MATERIALS_DB: MaterialItem[] = [
  // ═══════════════════════════════════════════
  // PLUMBING
  // ═══════════════════════════════════════════

  // Toilet
  { name: "Toilet (complete)", price: 180, category: "Plumbing", keywords: ["toilet", "commode", "replace toilet"] },
  { name: "Fill valve", price: 9, sku: "147966", category: "Plumbing", keywords: ["fill valve", "toilet running", "tank fill"] },
  { name: "Flapper", price: 7, sku: "420456", category: "Plumbing", keywords: ["flapper", "toilet leak", "running toilet"] },
  { name: "Tank lever", price: 8, category: "Plumbing", keywords: ["tank lever", "flush handle", "toilet handle"] },
  { name: "Toilet floor bolts", price: 4, category: "Plumbing", keywords: ["floor bolt", "closet bolt", "toilet bolt"] },
  { name: "Tank to bowl bolts", price: 6, category: "Plumbing", keywords: ["tank bolt", "tank to bowl"] },
  { name: "Toilet supply line", price: 8, category: "Plumbing", keywords: ["toilet supply", "supply line", "water supply"] },
  { name: "Quarter turn stop valve", price: 12, category: "Plumbing", keywords: ["shut off", "stop valve", "quarter turn", "shutoff"] },
  { name: "Quarter turn double stop", price: 18, category: "Plumbing", keywords: ["double stop", "double shut"] },
  { name: "Flange repair kit", price: 10, category: "Plumbing", keywords: ["flange repair", "toilet flange"] },
  { name: "Toilet flange", price: 8, category: "Plumbing", keywords: ["flange", "closet flange"] },
  { name: "Toilet bolt caps", price: 3, category: "Plumbing", keywords: ["bolt cap", "toilet cap"] },
  { name: "Rubber toilet seal (wax-free)", price: 8, category: "Plumbing", keywords: ["wax ring", "toilet seal", "rubber seal"] },
  { name: "Toilet gasket", price: 5, category: "Plumbing", keywords: ["tank gasket", "toilet gasket"] },
  { name: "Toilet lid", price: 12, category: "Plumbing", keywords: ["toilet lid", "tank lid", "tank cover"] },
  { name: "Toilet seat", price: 13, sku: "634072", category: "Plumbing", keywords: ["toilet seat"] },

  // Tub/Shower
  { name: "Tub surround kit", price: 250, category: "Plumbing", keywords: ["tub surround", "shower surround"] },
  { name: "Silicone caulk (white)", price: 6, category: "Plumbing", keywords: ["caulk", "caulking", "silicone", "seal"] },
  { name: "Tile grout (10lb)", price: 16, category: "Plumbing", keywords: ["grout", "tile grout", "regrout"] },
  { name: "Tub handles (pair)", price: 15, category: "Plumbing", keywords: ["tub handle", "shower handle", "faucet handle"] },
  { name: "Tub stem escutcheon", price: 8, category: "Plumbing", keywords: ["escutcheon", "trim plate", "cover plate"] },
  { name: "Danco stem", price: 6, category: "Plumbing", keywords: ["danco stem", "faucet stem"] },
  { name: "Danco seats", price: 4, category: "Plumbing", keywords: ["danco seat", "faucet seat"] },
  { name: "Danco 1/2\" rubber washer", price: 3, category: "Plumbing", keywords: ["rubber washer", "faucet washer"] },
  { name: "Danco cartridge 10405", price: 18, category: "Plumbing", keywords: ["danco cartridge", "faucet cartridge", "cartridge"] },
  { name: "Danco diverter stem", price: 12, category: "Plumbing", keywords: ["diverter", "diverter stem"] },
  { name: "Tub face plate", price: 8, category: "Plumbing", keywords: ["tub face plate", "overflow plate"] },
  { name: "Tub rubber stopper", price: 5, category: "Plumbing", keywords: ["tub stopper", "drain stopper", "rubber stopper"] },
  { name: "Shower arm", price: 8, category: "Plumbing", keywords: ["shower arm"] },
  { name: "Shower head", price: 14, sku: "1002847992", category: "Plumbing", keywords: ["shower head", "showerhead"] },
  { name: "Shower rod", price: 15, category: "Plumbing", keywords: ["shower rod", "curtain rod"] },
  { name: "Tub spout", price: 18, category: "Plumbing", keywords: ["tub spout", "bathtub spout"] },
  { name: "Shower escutcheon 1/2\"", price: 6, category: "Plumbing", keywords: ["shower escutcheon"] },
  { name: "3\" nipple", price: 3, category: "Plumbing", keywords: ["nipple", "pipe nipple"] },
  { name: "4\" nipple", price: 4, category: "Plumbing", keywords: ["nipple", "pipe nipple"] },
  { name: "Tub strainer", price: 8, category: "Plumbing", keywords: ["tub strainer", "tub drain"] },

  // Faucets & Sink
  { name: "Kitchen faucet (2-handle w/ sprayer)", price: 79, sku: "1008028130", category: "Plumbing", keywords: ["kitchen faucet", "faucet with sprayer"] },
  { name: "Bathroom faucet", price: 27, sku: "217251", category: "Plumbing", keywords: ["bath faucet", "bathroom faucet", "lav faucet"] },
  { name: "Faucet supply line 20\"", price: 8, category: "Plumbing", keywords: ["faucet supply", "supply line"] },
  { name: "Kitchen sprayer hose", price: 15, category: "Plumbing", keywords: ["sprayer hose", "kitchen sprayer", "sprayer"] },
  { name: "Faucet sprayer holder", price: 5, category: "Plumbing", keywords: ["sprayer holder"] },
  { name: "1-1/4\" slip nut", price: 3, category: "Plumbing", keywords: ["slip nut", "slip joint"] },
  { name: "1-1/4\" P-trap", price: 8, category: "Plumbing", keywords: ["p-trap", "p trap", "drain trap"] },
  { name: "1-1/4\" extension tube", price: 5, category: "Plumbing", keywords: ["extension tube", "tailpiece"] },
  { name: "1-1/2\" P-trap", price: 10, category: "Plumbing", keywords: ["p-trap", "p trap", "kitchen drain"] },
  { name: "1-1/2\" extension tube", price: 6, category: "Plumbing", keywords: ["extension tube"] },
  { name: "1-1/2\" slip nut", price: 3, category: "Plumbing", keywords: ["slip nut"] },
  { name: "Pop-up drain assembly", price: 12, category: "Plumbing", keywords: ["pop up drain", "drain assembly", "pop-up"] },
  { name: "Pop-up ball joint rod 1/2\"", price: 5, category: "Plumbing", keywords: ["ball joint", "pop up rod"] },
  { name: "Dishwasher supply line", price: 12, category: "Plumbing", keywords: ["dishwasher supply", "dishwasher water"] },
  { name: "Dishwasher drain line", price: 10, category: "Plumbing", keywords: ["dishwasher drain"] },
  { name: "Plunger pop-up", price: 8, category: "Plumbing", keywords: ["plunger pop up"] },
  { name: "Strainer basket", price: 8, category: "Plumbing", keywords: ["strainer basket", "sink strainer"] },
  { name: "Disposal stopper", price: 5, category: "Plumbing", keywords: ["disposal stopper"] },
  { name: "Garbage disposal 1/2HP", price: 90, category: "Plumbing", keywords: ["garbage disposal", "disposal"] },
  { name: "Faucet springs & rubber seats", price: 5, category: "Plumbing", keywords: ["springs and seats", "faucet repair"] },
  { name: "Spray diverter", price: 6, category: "Plumbing", keywords: ["spray diverter"] },
  { name: "Faucet aerator (male/female)", price: 5, category: "Plumbing", keywords: ["aerator", "faucet aerator"] },
  { name: "Shower splash guard", price: 8, category: "Plumbing", keywords: ["splash guard", "shower splash"] },
  { name: "Toilet paper holder", price: 12, category: "Plumbing", keywords: ["tissue holder", "tp holder", "toilet paper holder"] },
  { name: "Tub overflow washer", price: 3, category: "Plumbing", keywords: ["overflow washer", "tub overflow"] },
  { name: "Towel bar 24\"", price: 15, category: "Plumbing", keywords: ["towel bar", "towel rack"] },

  // Water Heater
  { name: "Water heater (50 gal)", price: 500, category: "Plumbing", keywords: ["water heater", "hot water"] },
  { name: "Water heater upper thermostat", price: 12, category: "Plumbing", keywords: ["upper thermostat", "water heater thermostat"] },
  { name: "Water heater lower thermostat", price: 10, category: "Plumbing", keywords: ["lower thermostat"] },
  { name: "Water heater element 4500W", price: 15, category: "Plumbing", keywords: ["heating element", "water heater element"] },
  { name: "T&P relief valve 2\" shank", price: 12, category: "Plumbing", keywords: ["t and p valve", "relief valve", "t&p"] },

  // ═══════════════════════════════════════════
  // ELECTRICAL
  // ═══════════════════════════════════════════

  // Covers & Plates
  { name: "Light switch cover plate", price: 1, category: "Electrical", keywords: ["switch cover", "switch plate"] },
  { name: "Outlet cover plate", price: 1, category: "Electrical", keywords: ["outlet cover", "receptacle cover"] },
  { name: "Blank cover plate", price: 1, category: "Electrical", keywords: ["blank cover", "blank plate"] },
  { name: "GFI/double switch cover", price: 3, category: "Electrical", keywords: ["gfi cover", "combo cover"] },
  { name: "Square cover plate", price: 2, category: "Electrical", keywords: ["square cover"] },
  { name: "Double switch cover", price: 2, category: "Electrical", keywords: ["double switch cover", "2-gang cover"] },

  // Devices
  { name: "Standard outlet (receptacle)", price: 2, category: "Electrical", keywords: ["outlet", "receptacle", "plug"] },
  { name: "Light switch (single pole)", price: 2, category: "Electrical", keywords: ["light switch", "switch", "single pole"] },
  { name: "Outlet/switch combo", price: 5, category: "Electrical", keywords: ["combo", "outlet switch"] },
  { name: "Double switch single pole", price: 5, category: "Electrical", keywords: ["double switch"] },
  { name: "GFCI outlet", price: 38, sku: "1001370834", category: "Electrical", keywords: ["gfci", "gfi", "ground fault"] },
  { name: "Outlet box", price: 2, category: "Electrical", keywords: ["outlet box", "junction box", "electrical box"] },

  // Bulbs & Lighting
  { name: "LED A19 bulbs (4-pack)", price: 10, category: "Electrical", keywords: ["led bulb", "a19", "light bulb", "bulb"] },
  { name: "G25 globe bulbs", price: 8, category: "Electrical", keywords: ["g25", "globe bulb", "vanity bulb"] },
  { name: "Decorative candle bulb B10C", price: 5, category: "Electrical", keywords: ["candle bulb", "b10", "decorative bulb", "chandelier bulb"] },
  { name: "40W appliance bulb", price: 4, category: "Electrical", keywords: ["appliance bulb", "oven bulb", "fridge bulb"] },
  { name: "18\" fluorescent tube", price: 8, category: "Electrical", keywords: ["fluorescent", "tube light", "t8"] },

  // Fixtures
  { name: "Flush mount ceiling light", price: 33, sku: "1004160609", category: "Electrical", keywords: ["flush mount", "ceiling light", "light fixture"] },
  { name: "18\" LED under-cabinet light", price: 20, category: "Electrical", keywords: ["under cabinet", "led strip", "sink light"] },
  { name: "4-bulb vanity light fixture", price: 45, category: "Electrical", keywords: ["vanity light", "bathroom light", "4 bulb"] },
  { name: "Mini flush mount light", price: 18, category: "Electrical", sku: "805306", keywords: ["mini flush", "small ceiling light", "closet light"] },
  { name: "Closet pull chain light", price: 8, category: "Electrical", keywords: ["pull chain", "closet light"] },
  { name: "Pull chain", price: 3, category: "Electrical", keywords: ["pull chain"] },
  { name: "Ceiling fan 42\"", price: 85, category: "Electrical", keywords: ["ceiling fan", "fan"] },
  { name: "Bathroom exhaust fan", price: 45, category: "Electrical", keywords: ["exhaust fan", "vent fan", "bath fan"] },

  // Safety
  { name: "Smoke alarm (10yr sealed)", price: 26, sku: "328119796", category: "Electrical", keywords: ["smoke alarm", "smoke detector"] },
  { name: "Smoke & CO combo alarm", price: 20, sku: "1005173566", category: "Electrical", keywords: ["smoke co", "carbon monoxide", "combo alarm"] },
  { name: "Batteries AA (8-pack)", price: 6, category: "Electrical", keywords: ["aa battery", "batteries"] },
  { name: "Batteries AAA (8-pack)", price: 6, category: "Electrical", keywords: ["aaa battery"] },
  { name: "9V battery (2-pack)", price: 6, category: "Electrical", keywords: ["9v battery", "9 volt"] },

  // Wire & Misc
  { name: "18 gauge wire (50ft)", price: 12, category: "Electrical", keywords: ["18 gauge", "wire", "thermostat wire"] },
  { name: "Wire nut assortment", price: 5, category: "Electrical", keywords: ["wire nut", "wire connector"] },

  // ═══════════════════════════════════════════
  // HVAC
  // ═══════════════════════════════════════════
  { name: "Fuse R20", price: 3, category: "HVAC", keywords: ["fuse r20", "20 amp fuse"] },
  { name: "Fuse R30", price: 3, category: "HVAC", keywords: ["fuse r30", "30 amp fuse"] },
  { name: "Thermostat T701", price: 28, category: "HVAC", keywords: ["thermostat", "t701"] },
  { name: "Transformer 50354", price: 18, category: "HVAC", keywords: ["transformer", "24v transformer"] },
  { name: "Switching relay (general purpose)", price: 22, category: "HVAC", keywords: ["relay", "switching relay"] },
  { name: "Contactor", price: 25, category: "HVAC", keywords: ["contactor", "ac contactor"] },
  { name: "Sequencer", price: 28, category: "HVAC", keywords: ["sequencer", "heat sequencer"] },
  { name: "Capacitor 35+5 MFD", price: 15, category: "HVAC", keywords: ["capacitor", "35+5", "dual capacitor"] },
  { name: "Capacitor 30+5 MFD", price: 15, category: "HVAC", keywords: ["30+5", "capacitor"] },
  { name: "Capacitor 40+5 MFD", price: 16, category: "HVAC", keywords: ["40+5", "capacitor"] },
  { name: "Capacitor 30 MFD", price: 12, category: "HVAC", keywords: ["30 mfd", "run capacitor"] },
  { name: "Capacitor 45 MFD", price: 14, category: "HVAC", keywords: ["45 mfd"] },
  { name: "Capacitor 5 MFD", price: 8, category: "HVAC", keywords: ["5 mfd", "start capacitor"] },
  { name: "AC Leak Freeze", price: 25, category: "HVAC", keywords: ["leak freeze", "ac leak", "refrigerant leak"] },
  { name: "R410A refrigerant (25lb)", price: 250, category: "HVAC", keywords: ["r410a", "refrigerant", "freon"] },
  { name: "MO99 refrigerant (25lb)", price: 200, category: "HVAC", keywords: ["mo99", "refrigerant"] },
  { name: "Vent register 10x6", price: 6, category: "HVAC", keywords: ["vent register", "register", "floor vent", "10x6"] },
  { name: "Vent register 8x6", price: 5, category: "HVAC", keywords: ["vent register", "8x6"] },
  { name: "HVAC air filter (standard)", price: 8, category: "HVAC", keywords: ["air filter", "hvac filter", "furnace filter"] },

  // ═══════════════════════════════════════════
  // HARDWARE / DOORS / WINDOWS
  // ═══════════════════════════════════════════
  { name: "Mailbox lock", price: 8, category: "Hardware", keywords: ["mailbox lock", "mailbox"] },
  { name: "Mirror (wall)", price: 35, category: "Hardware", keywords: ["mirror", "wall mirror"] },
  { name: "Medicine cabinet", price: 55, category: "Hardware", keywords: ["medicine cabinet"] },
  { name: "Passage door knob", price: 12, category: "Hardware", keywords: ["passage knob", "door knob", "hall knob"] },
  { name: "Privacy door knob", price: 14, category: "Hardware", keywords: ["privacy knob", "bedroom knob", "bath knob"] },
  { name: "Deadbolt smart lock", price: 160, category: "Hardware", keywords: ["smart lock", "deadbolt", "keypad lock"] },
  { name: "Standard deadbolt", price: 25, category: "Hardware", keywords: ["deadbolt", "dead bolt"] },
  { name: "Door stop", price: 3, category: "Hardware", keywords: ["door stop", "doorstop", "door bumper"] },
  { name: "Door chain", price: 8, category: "Hardware", keywords: ["door chain", "chain lock"] },
  { name: "Door sweep", price: 10, category: "Hardware", keywords: ["door sweep", "bottom seal"] },
  { name: "Interior door hinge", price: 4, category: "Hardware", keywords: ["interior hinge", "door hinge", "hinge"] },
  { name: "Exterior door hinge", price: 6, category: "Hardware", keywords: ["exterior hinge"] },
  { name: "Door weatherstripping", price: 10, category: "Hardware", keywords: ["weatherstrip", "weather strip", "door seal"] },
  { name: "Storm door closer", price: 15, category: "Hardware", keywords: ["door closer", "storm door closer"] },
  { name: "Patio door security bar", price: 12, category: "Hardware", keywords: ["security bar", "patio bar", "sliding door bar"] },
  { name: "Screen door handle", price: 8, category: "Hardware", keywords: ["screen handle", "screen door handle"] },
  { name: "Screen door wheels", price: 6, category: "Hardware", keywords: ["screen wheels", "door wheels", "roller"] },
  { name: "Storm door chain stop", price: 5, category: "Hardware", keywords: ["chain stop", "storm chain"] },
  { name: "Bifold closet door pin", price: 3, category: "Hardware", keywords: ["bifold pin", "closet pin"] },
  { name: "Bifold pin holder", price: 3, category: "Hardware", keywords: ["pin holder", "bifold bracket"] },
  { name: "Bifold track", price: 8, category: "Hardware", keywords: ["bifold track"] },
  { name: "Bifold repair kit", price: 6, category: "Hardware", keywords: ["bifold repair", "bifold kit"] },
  { name: "Brushed nickel cabinet knobs (10pk)", price: 18, category: "Hardware", keywords: ["cabinet knob", "brushed nickel knob"] },
  { name: "Brushed nickel cabinet handles (10pk)", price: 22, category: "Hardware", keywords: ["cabinet handle", "cabinet pull", "brushed nickel handle"] },
  { name: "Cabinet hinges (pair)", price: 5, category: "Hardware", keywords: ["cabinet hinge"] },
  { name: "Cabinet magnetic catch", price: 3, category: "Hardware", keywords: ["cabinet magnet", "magnetic catch"] },
  { name: "Power Grab adhesive", price: 7, category: "Hardware", keywords: ["power grab", "construction adhesive"] },
  { name: "Cove base (4ft)", price: 3, category: "Hardware", keywords: ["cove base", "baseboard"] },
  { name: "Cove base adhesive", price: 8, category: "Hardware", keywords: ["cove adhesive", "base adhesive"] },
  { name: "Nuts & bolts assortment", price: 12, category: "Hardware", keywords: ["nuts bolts", "assortment", "hardware kit"] },
  { name: "Drywall screws 1\" (1lb)", price: 6, category: "Hardware", keywords: ["drywall screw", "1 inch screw"] },
  { name: "Drywall screws 2\" (1lb)", price: 7, category: "Hardware", keywords: ["drywall screw", "2 inch screw"] },
  { name: "Drywall screws 3\" (1lb)", price: 8, category: "Hardware", keywords: ["drywall screw", "3 inch screw"] },

  // Blinds
  { name: "Vertical blinds 78\"x84\"", price: 45, category: "Hardware", keywords: ["vertical blind", "patio blind"] },
  { name: "Vertical blind slats (pack)", price: 15, category: "Hardware", keywords: ["blind slat", "vertical slat"] },
  { name: "Cordless blind 72\"x48\"", price: 28, category: "Hardware", keywords: ["72 blind", "72x48"] },
  { name: "Cordless blind 46\"x48\"", price: 22, category: "Hardware", keywords: ["46 blind", "46x48"] },
  { name: "Cordless blind 43\"x48\"", price: 20, category: "Hardware", keywords: ["43 blind", "43x48"] },
  { name: "Cordless blind 35\"x48\"", price: 18, category: "Hardware", keywords: ["35 blind", "35x48", "35 inch"] },
  { name: "Cordless blind 27\"x72\"", price: 16, category: "Hardware", keywords: ["27 blind", "27x72"] },

  // ═══════════════════════════════════════════
  // APPLIANCES / PARTS
  // ═══════════════════════════════════════════
  { name: "GE 8\" drip pan", price: 8, category: "Appliances", keywords: ["8 drip pan", "drip pan", "stove drip"] },
  { name: "GE 6\" drip pan", price: 6, category: "Appliances", keywords: ["6 drip pan"] },
  { name: "GE 8\" burner element", price: 18, category: "Appliances", keywords: ["8 burner", "burner element", "stove burner"] },
  { name: "GE 6\" burner element", price: 14, category: "Appliances", keywords: ["6 burner"] },
  { name: "Oven bake element", price: 22, category: "Appliances", keywords: ["bake element", "oven element", "lower element"] },
  { name: "Oven broil element", price: 20, category: "Appliances", keywords: ["broil element", "upper element"] },
  { name: "Oven control board", price: 85, category: "Appliances", keywords: ["control board", "oven board"] },
  { name: "Dishwasher timer", price: 45, category: "Appliances", keywords: ["dishwasher timer"] },
  { name: "Dishwasher soap dispenser", price: 15, category: "Appliances", keywords: ["soap dispenser", "detergent dispenser"] },
  { name: "Dishwasher drain pump", price: 35, category: "Appliances", keywords: ["drain pump", "dishwasher pump"] },
  { name: "Dishwasher door gasket", price: 18, category: "Appliances", keywords: ["dishwasher gasket", "door gasket", "door seal"] },
  { name: "Refrigerator door gasket", price: 45, category: "Appliances", keywords: ["fridge gasket", "refrigerator gasket", "fridge seal"] },
  { name: "Evaporator fan motor", price: 35, category: "Appliances", keywords: ["evaporator fan", "fridge fan", "fan motor"] },
  { name: "Range hood 30\" filter", price: 13, category: "Appliances", keywords: ["range hood filter", "hood filter", "grease filter"] },
  { name: "Universal stove knob", price: 6, category: "Appliances", keywords: ["stove knob", "range knob", "burner knob"] },
  { name: "Dishwasher rack adjuster clip kit", price: 12, category: "Appliances", keywords: ["rack adjuster", "dishwasher rack", "rack clip"] },

  // ═══════════════════════════════════════════
  // PAINT
  // ═══════════════════════════════════════════
  { name: "Interior paint 5-gal (semi-gloss)", price: 153, sku: "654396", category: "Paint", keywords: ["5 gallon", "5-gal", "interior paint", "semi gloss"] },
  { name: "Interior paint 1-gal", price: 41, sku: "654973", category: "Paint", keywords: ["1 gallon", "1-gal", "paint gallon"] },
  { name: "Kilz spray primer", price: 8, category: "Paint", keywords: ["kilz", "spray primer", "primer spray"] },
  { name: "White semi-gloss spray paint", price: 6, category: "Paint", keywords: ["spray paint", "white spray"] },
  { name: "Primer (gallon)", price: 16, category: "Paint", keywords: ["primer", "prime"] },
  { name: "Primer (quart)", price: 10, category: "Paint", keywords: ["primer qt", "primer quart"] },
  { name: "18\" roller cover", price: 8, category: "Paint", keywords: ["18 roller", "large roller", "dreadlock roller"] },
  { name: "9\" roller cover", price: 5, category: "Paint", keywords: ["9 roller", "roller cover"] },
  { name: "4\" mini roller", price: 4, category: "Paint", keywords: ["4 roller", "mini roller", "trim roller"] },
  { name: "3\" paint brush (angled)", price: 8, category: "Paint", keywords: ["3 brush", "paint brush", "angled brush"] },
  { name: "2\" cut-in brush", price: 6, category: "Paint", keywords: ["2 brush", "cut in", "cutting brush"] },
  { name: "4\" wall patch (2-pack)", price: 5, category: "Paint", keywords: ["wall patch", "drywall patch"] },
  { name: "Drywall joint compound (4.5 gal ready-mix)", price: 22, sku: "258725", category: "Paint", keywords: ["drywall mud", "joint compound", "mud"] },
  { name: "Drywall sheet (4x8)", price: 12, sku: "893749", category: "Paint", keywords: ["drywall", "sheetrock", "drywall sheet"] },
  { name: "Drywall sanding sponge", price: 5, category: "Paint", keywords: ["sanding sponge", "drywall sponge"] },
  { name: "Painter's tape (60yd)", price: 8, sku: "202391340", category: "Paint", keywords: ["painter tape", "blue tape", "masking tape"] },
  { name: "Drop cloth (9x12)", price: 10, category: "Paint", keywords: ["drop cloth", "plastic sheeting"] },
  { name: "Spackle tub", price: 8, category: "Paint", keywords: ["spackle", "spackling"] },

  // ═══════════════════════════════════════════
  // FLOORING
  // ═══════════════════════════════════════════
  { name: "LVP flooring (per sqft)", price: 2, category: "Flooring", keywords: ["lvp", "vinyl plank", "laminate", "flooring"] },
  { name: "Underlayment (per sqft)", price: 0.30, category: "Flooring", keywords: ["underlayment", "underlay"] },
  { name: "Transition strip", price: 15, category: "Flooring", keywords: ["transition", "t-mold", "reducer"] },
  { name: "Cove base (4ft)", price: 3, category: "Flooring", keywords: ["cove base"] },
  { name: "Cove base adhesive", price: 8, category: "Flooring", keywords: ["cove adhesive"] },
  { name: "Carpet (per sq yd)", price: 28, category: "Flooring", keywords: ["carpet"] },
  { name: "Carpet pad (per sq yd)", price: 8, category: "Flooring", keywords: ["carpet pad"] },

  // ═══════════════════════════════════════════
  // JANITORIAL
  // ═══════════════════════════════════════════
  { name: "Paper towels (6-roll)", price: 10, category: "Janitorial", keywords: ["paper towel"] },
  { name: "Nitrile gloves (box)", price: 12, category: "Janitorial", keywords: ["gloves", "nitrile"] },
  { name: "Shop vac bags 1.5gal (3pk)", price: 8, category: "Janitorial", keywords: ["shop vac bag", "vacuum bag"] },
  { name: "55-gallon trash bags (20ct)", price: 15, category: "Janitorial", keywords: ["trash bag", "garbage bag"] },
  { name: "All-purpose cleaner", price: 5, category: "Janitorial", keywords: ["all purpose", "cleaner"] },
  { name: "Hand soap", price: 4, category: "Janitorial", keywords: ["hand soap"] },
  { name: "Scrubbing brush", price: 5, category: "Janitorial", keywords: ["scrub brush", "cleaning brush"] },
  { name: "Cloth rags (bag)", price: 10, category: "Janitorial", keywords: ["rags", "cloth rag"] },
  { name: "Dishwasher cleaner", price: 5, category: "Janitorial", keywords: ["dishwasher magic", "dishwasher clean"] },
  { name: "Disposal cleaner", price: 4, category: "Janitorial", keywords: ["disposal cleaner"] },

  // ═══════════════════════════════════════════
  // SAFETY
  // ═══════════════════════════════════════════
  { name: "Fire extinguisher (2.5lb ABC)", price: 24, sku: "1002763584", category: "Safety", keywords: ["fire extinguisher"] },

  // ═══════════════════════════════════════════
  // HOME DEPOT PURCHASE-DATA ADDITIONS
  // Real Wichita costs from Bernard's HD Pro purchase history (2025–2026)
  // ═══════════════════════════════════════════
  { name: "FibaTape wall repair fabric (6in x 75ft)", price: 13, sku: "311223236", category: "Paint", keywords: ["fibatape", "wall repair fabric", "mesh drywall tape"] },
  { name: "Orange peel texture spray (25oz)", price: 28, sku: "203425183", category: "Paint", keywords: ["orange peel", "wall texture", "texture spray"] },
  { name: "Paint tray + roller kit (6-piece)", price: 12, sku: "319877662", category: "Paint", keywords: ["roller tray", "tray kit", "roller kit"] },
  { name: "Paintable latex caulk (10oz)", price: 4, sku: "316993414", category: "Paint", keywords: ["latex caulk", "paintable caulk", "acrylic caulk"] },
  { name: "DYNAFLEX exterior sealant (10oz)", price: 8, sku: "306283633", category: "Paint", keywords: ["dynaflex", "exterior sealant", "siding sealant"] },
  { name: "Hollow-core interior door slab (30x80)", price: 80, sku: "330336362", category: "Hardware", keywords: ["door slab", "hollow core door", "new door"] },
  { name: "Keyed entry + deadbolt combo pack", price: 36, sku: "317194063", category: "Hardware", keywords: ["keyed entry", "entry combo", "lock combo", "rekey lock"] },
  { name: "Thread seal tape (PTFE)", price: 2, sku: "202280370", category: "Plumbing", keywords: ["thread tape", "teflon tape", "plumber tape"] },
  { name: "3-tab roofing shingles (bundle)", price: 36, sku: "311703832", category: "Roofing", keywords: ["roofing shingle", "3-tab shingle", "shingle bundle"] },
  { name: "Roof cement / flashing sealant (10oz)", price: 3, sku: "202091010", category: "Roofing", keywords: ["roof cement", "flashing cement", "roof patch"] },
  { name: "Roof collar / pipe flashing", price: 8, sku: "331181638", category: "Roofing", keywords: ["roof collar", "pipe flashing", "vent flashing"] },
  { name: "Fan speed/light switch", price: 10, sku: "306596875", category: "Electrical", keywords: ["fan switch", "fan light switch", "pull chain fan"] },
  { name: "Interior door knob (6-pack)", price: 50, sku: "302473173", category: "Hardware", keywords: ["door knob 6 pack", "knob multipack", "bulk door knob"] },
  { name: "Foam backer rod (20ft)", price: 5, sku: "100165680", category: "Hardware", keywords: ["backer rod", "foam backer", "gap filler rod"] },
  { name: "Bathroom vanity (19in w/ top)", price: 139, sku: "203486514", category: "Plumbing", keywords: ["bath vanity", "sink vanity", "vanity cabinet"] },
  { name: "Toilet seat (soft-close)", price: 25, sku: "336719906", category: "Plumbing", keywords: ["soft close seat", "soft-close toilet", "slow close seat"] },
  { name: "Pine shims (12-pack)", price: 3, sku: "300723328", category: "Hardware", keywords: ["shims", "pine shims", "wood shims"] },
  { name: "OSB sheet 1/2in (4x8)", price: 12, sku: "100012207", category: "Flooring", keywords: ["osb board", "oriented strand", "subfloor sheet"] },
  { name: "Window screen frame kit", price: 16, sku: "206613125", category: "Hardware", keywords: ["screen frame", "window screen kit", "screen frame kit"] },
  { name: "Fiberglass screen roll (36inx7ft)", price: 15, sku: "323360928", category: "Hardware", keywords: ["screen roll", "fiberglass screen", "screen mesh"] },
  { name: "Shoe molding (per ft)", price: 0.55, sku: "100648759", category: "Flooring", keywords: ["shoe molding", "base shoe", "quarter round"] },
  { name: "Laminate transition molding (4-in-1)", price: 40, sku: "339218035", category: "Flooring", keywords: ["4-in-1 molding", "laminate transition", "laminate molding"] },
  { name: "Flex Seal rubber sealant spray", price: 15, sku: "203144520", category: "Paint", keywords: ["flex seal", "rubber sealant spray", "leak seal spray"] },
  { name: "Kitchen side sprayer", price: 8, sku: "318763115", category: "Plumbing", keywords: ["side spray", "kitchen side sprayer", "sink side spray"] },

  // ═══════════════════════════════════════════
  // LEGACY ESTIMATOR — CONSOLIDATED (migrated from parser.ts estimateMaterials)
  // ═══════════════════════════════════════════
  // ── Appliances ──
  { name: "Appliance power cord", price: 22, category: "Appliances", keywords: ["appliance cord", "range cord"] },
  { name: "Dryer vent kit", price: 22, category: "Appliances", keywords: ["dryer vent", "dryer duct"] },
  { name: "Dryer power cord", price: 25, category: "Appliances", keywords: ["dryer cord"] },
  { name: "Washer hoses (pair)", price: 20, category: "Appliances", keywords: ["washer hose", "washing machine hose"] },
  { name: "Washer outlet box", price: 28, category: "Appliances", keywords: ["washer box", "washing machine box"] },
  { name: "Range power cord", price: 22, category: "Appliances", keywords: ["range cord", "stove cord"] },
  { name: "Refrigerator water line", price: 15, category: "Appliances", keywords: ["refrigerator line", "fridge line"] },
  // ── Bath ──
  { name: "Towel ring", price: 14, category: "Bath", keywords: ["towel ring"] },
  { name: "Robe/towel hook", price: 10, category: "Bath", keywords: ["towel hook", "robe hook"] },
  { name: "Vanity mirror", price: 65, category: "Bath", keywords: ["vanity mirror", "bath mirror"] },
  { name: "Grab bar (18in)", price: 22, category: "Bath", keywords: ["grab bar", "safety bar"] },
  { name: "Soap dish", price: 10, category: "Bath", keywords: ["soap dish"] },
  { name: "Bath accessory set (5pc)", price: 40, category: "Bath", keywords: ["bath accessory set", "accessory set"] },
  { name: "Floor heating mat (kit)", price: 200, category: "Bath", keywords: ["heated floor", "floor heat"] },
  // ── Concrete ──
  { name: "Precast step", price: 60, category: "Concrete", keywords: ["concrete step", "precast step"] },
  { name: "Concrete mix (80lb bag)", price: 7, category: "Concrete", keywords: ["concrete mix", "bag concrete", "quikrete"] },
  { name: "Concrete patch (qt)", price: 12, category: "Concrete", keywords: ["concrete patch", "patch concrete"] },
  { name: "Concrete crack filler", price: 8, category: "Concrete", keywords: ["concrete crack", "crack fill"] },
  { name: "Concrete sealer (gal)", price: 35, category: "Concrete", keywords: ["concrete seal", "seal concrete"] },
  { name: "Rebar #4 (10ft)", price: 8, category: "Concrete", keywords: ["rebar"] },
  { name: "Wire mesh (5x10 sheet)", price: 12, category: "Concrete", keywords: ["wire mesh", "welded wire"] },
  { name: "Anchor bolts (10pk)", price: 10, category: "Concrete", keywords: ["anchor bolt"] },
  { name: "Sonotube (12in x 4ft)", price: 28, category: "Concrete", keywords: ["form tube", "sonotube", "sono tube"] },
  { name: "Fast-set post mix (50lb)", price: 8, category: "Concrete", keywords: ["post hole", "post mix"] },
  // ── Doors ──
  { name: "Interior prehung door", price: 120, category: "Doors", keywords: ["prehung", "prehung door"] },
  { name: "Exterior door", price: 350, category: "Doors", keywords: ["exterior door"] },
  { name: "Storm door", price: 180, category: "Doors", keywords: ["storm door"] },
  { name: "Sliding patio door", price: 550, category: "Doors", keywords: ["sliding door", "patio door"] },
  { name: "French door", price: 450, category: "Doors", keywords: ["french door"] },
  { name: "Pocket door kit", price: 175, category: "Doors", keywords: ["pocket door"] },
  { name: "Barn door + hardware", price: 220, category: "Doors", keywords: ["barn door"] },
  { name: "Garage door", price: 800, category: "Doors", keywords: ["garage door"] },
  { name: "Garage door opener", price: 250, category: "Doors", keywords: ["garage door opener", "door opener"] },
  { name: "Bifold door", price: 70, category: "Doors", keywords: ["bifold door"] },
  { name: "Pet door", price: 45, category: "Doors", keywords: ["pet door", "doggy door"] },
  { name: "Door jamb kit", price: 35, category: "Doors", keywords: ["door jamb"] },
  { name: "Door frame", price: 30, category: "Doors", keywords: ["door frame"] },
  // ── Drywall ──
  { name: "Moisture-resist drywall (4x8)", price: 18, category: "Drywall", keywords: ["moisture resist", "green board", "greenboard"] },
  { name: "Cement board (3x5)", price: 14, category: "Drywall", keywords: ["cement board", "hardi backer", "hardibacker", "backer board"] },
  { name: "Drywall tape (roll)", price: 5, category: "Drywall", keywords: ["drywall tape", "paper tape"] },
  { name: "Mesh tape (roll)", price: 6, category: "Drywall", keywords: ["mesh tape"] },
  { name: "Corner bead (8ft)", price: 5, category: "Drywall", keywords: ["corner bead"] },
  // ── Electrical ──
  { name: "AFCI outlet", price: 28, category: "Electrical", keywords: ["afci", "arc fault", "arc-fault"] },
  { name: "USB outlet", price: 22, category: "Electrical", keywords: ["usb outlet", "usb receptacle", "usb charger outlet"] },
  { name: "Outdoor outlet+cover (WP)", price: 22, category: "Electrical", keywords: ["outdoor outlet", "exterior outlet", "weatherproof outlet", "wp outlet"] },
  { name: "3-way switch", price: 10, category: "Electrical", keywords: ["3-way switch", "three way switch", "3 way switch"] },
  { name: "Dimmer switch", price: 22, category: "Electrical", keywords: ["dimmer"] },
  { name: "Smart switch", price: 35, category: "Electrical", keywords: ["smart switch", "wifi switch"] },
  { name: "Timer switch", price: 18, category: "Electrical", keywords: ["timer switch"] },
  { name: "Motion sensor switch", price: 20, category: "Electrical", keywords: ["motion sensor switch", "occupancy sensor", "motion switch"] },
  { name: "Pendant light", price: 50, category: "Electrical", keywords: ["pendant light", "pendant fixture", "hanging pendant"] },
  { name: "Track light kit", price: 65, category: "Electrical", keywords: ["track light", "track lighting"] },
  { name: "Recessed light kit", price: 28, category: "Electrical", keywords: ["recessed light", "recessed can", "can light"] },
  { name: "LED flood light", price: 30, category: "Electrical", keywords: ["flood light", "floodlight", "security light"] },
  { name: "Breaker panel (200A)", price: 220, category: "Electrical", keywords: ["breaker panel", "breaker box", "electrical panel", "service panel"] },
  { name: "Circuit breaker", price: 12, category: "Electrical", keywords: ["circuit breaker", "single breaker", "new breaker"] },
  { name: "GFCI breaker", price: 45, category: "Electrical", keywords: ["gfci breaker", "gfi breaker"] },
  { name: "Sub-panel (60A)", price: 120, category: "Electrical", keywords: ["sub-panel", "subpanel", "sub panel"] },
  { name: "Romex wire (50ft)", price: 35, category: "Electrical", keywords: ["romex", "14/2", "12/2", "wire run"] },
  { name: "3-conductor wire (50ft)", price: 48, category: "Electrical", keywords: ["14/3", "12/3"] },
  { name: "10/2 wire (50ft)", price: 55, category: "Electrical", keywords: ["10/2", "10 gauge"] },
  { name: "THHN wire (50ft)", price: 20, category: "Electrical", keywords: ["thhn", "individual wire"] },
  { name: "EMT conduit (10ft)", price: 12, category: "Electrical", keywords: ["conduit"] },
  { name: "Surge protector (WH)", price: 80, category: "Electrical", keywords: ["surge protect", "whole house surge", "surge protector"] },
  { name: "Doorbell", price: 25, category: "Electrical", keywords: ["doorbell", "door bell", "chime button"] },
  { name: "Video doorbell", price: 150, category: "Electrical", keywords: ["video doorbell", "smart doorbell"] },
  { name: "Meter base", price: 85, category: "Electrical", keywords: ["meter base", "electric meter", "meter socket"] },
  { name: "Ground rod (8ft)", price: 15, category: "Electrical", keywords: ["ground rod", "grounding rod"] },
  { name: "Transfer switch", price: 250, category: "Electrical", keywords: ["transfer switch", "generator switch"] },
  { name: "EV charger (Level 2)", price: 450, category: "Electrical", keywords: ["ev charger", "car charger", "level 2 charger"] },
  // ── Exterior ──
  { name: "Outdoor wall light", price: 35, category: "Exterior", keywords: ["outdoor light", "porch light", "exterior light"] },
  { name: "Path light (solar)", price: 8, category: "Exterior", keywords: ["landscape light", "path light", "pathway light"] },
  { name: "Motion flood light", price: 35, category: "Exterior", keywords: ["motion flood", "motion light", "motion floodlight"] },
  { name: "Vinyl siding (sq)", price: 95, category: "Exterior", keywords: ["vinyl siding"] },
  { name: "Fiber cement siding (sq)", price: 140, category: "Exterior", keywords: ["fiber cement", "hardie", "cement siding"] },
  { name: "Wood lap siding (8ft)", price: 12, category: "Exterior", keywords: ["wood siding", "lap siding"] },
  { name: "T1-11 siding (4x8)", price: 65, category: "Exterior", keywords: ["t1-11", "t-111", "t1-11 siding"] },
  { name: "Downspout (10ft)", price: 22, category: "Exterior", keywords: ["downspout"] },
  { name: "Gutter section (10ft)", price: 18, category: "Exterior", keywords: ["gutter section", "rain gutter", "gutter run"] },
  { name: "Gutter guard (4ft)", price: 8, category: "Exterior", keywords: ["gutter guard", "leaf guard"] },
  { name: "House numbers", price: 12, category: "Exterior", keywords: ["house number", "address number"] },
  { name: "Mailbox+post", price: 45, category: "Exterior", keywords: ["mailbox post", "new mailbox"] },
  { name: "Fence picket (6ft)", price: 5, category: "Exterior", keywords: ["fence board", "picket"] },
  { name: "Fence post (4x4 8ft)", price: 14, category: "Exterior", keywords: ["fence post"] },
  { name: "Privacy fence panel (6x8)", price: 65, category: "Exterior", keywords: ["fence panel", "privacy fence"] },
  { name: "Chain link fence (50ft roll)", price: 80, category: "Exterior", keywords: ["chain link"] },
  { name: "Gate hardware kit", price: 22, category: "Exterior", keywords: ["gate hardware", "fence gate", "gate latch"] },
  { name: "Composite deck board (12ft)", price: 30, category: "Exterior", keywords: ["deck board", "composite deck"] },
  { name: "PT lumber 2x6 (8ft)", price: 10, category: "Exterior", keywords: ["pressure treat", "pt lumber"] },
  { name: "Deck screws (5lb)", price: 28, category: "Exterior", keywords: ["deck screw"] },
  { name: "Joist tape (roll)", price: 22, category: "Exterior", keywords: ["joist tape"] },
  { name: "Post cap", price: 8, category: "Exterior", keywords: ["post cap"] },
  { name: "Lattice panel (4x8)", price: 25, category: "Exterior", keywords: ["lattice"] },
  { name: "Landscape timber (8ft)", price: 8, category: "Exterior", keywords: ["landscape timber"] },
  { name: "French drain pipe (10ft)", price: 15, category: "Exterior", keywords: ["french drain"] },
  { name: "Mulch (bag)", price: 5, category: "Exterior", keywords: ["mulch"] },
  { name: "Pressure washer detergent", price: 12, category: "Exterior", keywords: ["power wash", "pressure wash"] },
  { name: "House wrap (roll)", price: 120, category: "Exterior", keywords: ["house wrap", "tyvek"] },
  { name: "Weather vane", price: 45, category: "Exterior", keywords: ["weather vane", "weathervane"] },
  { name: "Zip system tape", price: 22, category: "Exterior", keywords: ["house wrap tape", "zip system tape"] },
  // ── Flooring ──
  { name: "Carpet tack strip (4ft)", price: 3, category: "Flooring", keywords: ["tack strip", "carpet tack"] },
  { name: "Seam tape", price: 8, category: "Flooring", keywords: ["seam tape"] },
  { name: "Carpet patch kit", price: 15, category: "Flooring", keywords: ["carpet patch", "carpet repair"] },
  { name: "Floor tile (sq ft)", price: 4, category: "Flooring", keywords: ["floor tile", "tile floor"] },
  { name: "Thinset mortar (50lb)", price: 18, category: "Flooring", keywords: ["thinset", "thinset mortar"] },
  { name: "Tile spacers", price: 5, category: "Flooring", keywords: ["tile spacer"] },
  { name: "Wall tile (sq ft)", price: 5, category: "Flooring", keywords: ["wall tile", "tile wall"] },
  { name: "Hardwood flooring (sq ft)", price: 8, category: "Flooring", keywords: ["hardwood floor", "oak floor", "wood floor"] },
  { name: "Floor nails/staples", price: 12, category: "Flooring", keywords: ["floor nails", "floor staples"] },
  { name: "Engineered hardwood (sq ft)", price: 6, category: "Flooring", keywords: ["engineered wood", "engineered floor"] },
  { name: "Sheet vinyl (sq yd)", price: 18, category: "Flooring", keywords: ["sheet vinyl", "vinyl sheet"] },
  { name: "Linoleum (sq yd)", price: 22, category: "Flooring", keywords: ["linoleum"] },
  { name: "Door threshold", price: 18, category: "Flooring", keywords: ["threshold"] },
  { name: "Grout sealer", price: 14, category: "Flooring", keywords: ["grout sealer", "grout seal"] },
  { name: "Self-leveling compound (50lb)", price: 35, category: "Flooring", keywords: ["self-level", "self leveling", "floor leveling"] },
  { name: "Floor adhesive (gal)", price: 28, category: "Flooring", keywords: ["floor adhesive", "flooring glue"] },
  { name: "Stair nosing", price: 16, category: "Flooring", keywords: ["stair nose", "stair nosing", "stair tread"] },
  { name: "Rubber flooring tile", price: 6, category: "Flooring", keywords: ["rubber floor", "gym floor"] },
  { name: "Peel & stick tile (box)", price: 28, category: "Flooring", keywords: ["peel and stick", "peel stick"] },
  { name: "Floor sanding discs", price: 15, category: "Flooring", keywords: ["floor sanding", "refinish floor", "sand floor"] },
  // ── Framing ──
  { name: "2x4 stud (8ft)", price: 5, category: "Framing", keywords: ["framing lumber", "wall stud"] },
  { name: "2x10 (8ft)", price: 16, category: "Framing", keywords: ["2x10"] },
  { name: "2x12 (8ft)", price: 20, category: "Framing", keywords: ["2x12"] },
  { name: "LVL beam (12ft)", price: 65, category: "Framing", keywords: ["lvl beam", "header beam"] },
  { name: "Plywood (4x8 3/4in)", price: 55, category: "Framing", keywords: ["plywood"] },
  { name: "Furring strip 1x2 (8ft)", price: 3, category: "Framing", keywords: ["furring strip"] },
  { name: "Metal stud (8ft)", price: 6, category: "Framing", keywords: ["metal stud", "steel stud"] },
  { name: "Metal track (10ft)", price: 7, category: "Framing", keywords: ["metal track", "steel track"] },
  { name: "Joist hanger", price: 4, category: "Framing", keywords: ["joist hanger"] },
  { name: "Hurricane strap", price: 3, category: "Framing", keywords: ["hurricane strap", "tie down"] },
  { name: "Structural bracket", price: 8, category: "Framing", keywords: ["simpson tie", "structural bracket"] },
  { name: "Framing nails (5lb)", price: 12, category: "Framing", keywords: ["framing nail", "common nail"] },
  // ── Gas ──
  { name: "Gas flex line", price: 25, category: "Gas", keywords: ["gas flex", "gas line", "gas pipe"] },
  { name: "Gas valve", price: 35, category: "Gas", keywords: ["gas valve"] },
  { name: "Gas connector", price: 20, category: "Gas", keywords: ["gas connector"] },
  { name: "Gas shut-off valve", price: 22, category: "Gas", keywords: ["gas shutoff", "gas shut-off"] },
  { name: "Black iron pipe (10ft)", price: 18, category: "Gas", keywords: ["black pipe", "black iron pipe"] },
  { name: "Black iron fitting", price: 6, category: "Gas", keywords: ["gas fitting", "black fitting", "black iron fitting"] },
  { name: "Gas leak detector spray", price: 8, category: "Gas", keywords: ["gas leak detect", "leak detector spray"] },
  { name: "CSST gas line (per ft)", price: 5, category: "Gas", keywords: ["csst", "corrugated gas"] },
  // ── HVAC ──
  { name: "Smart thermostat", price: 140, category: "HVAC", keywords: ["smart thermostat", "nest", "ecobee", "wifi thermostat"] },
  { name: "Condenser unit", price: 1400, category: "HVAC", keywords: ["condenser", "outside unit", "ac unit"] },
  { name: "Evaporator coil", price: 450, category: "HVAC", keywords: ["evaporator coil", "a-coil", "a coil"] },
  { name: "Duct section (4ft)", price: 25, category: "HVAC", keywords: ["ductwork", "duct run"] },
  { name: "Flex duct (25ft)", price: 35, category: "HVAC", keywords: ["flex duct"] },
  { name: "Foil duct tape", price: 10, category: "HVAC", keywords: ["foil tape", "duct tape"] },
  { name: "Duct mastic (gal)", price: 15, category: "HVAC", keywords: ["duct mastic", "duct seal"] },
  { name: "Return air grille", price: 14, category: "HVAC", keywords: ["return grille", "return air"] },
  { name: "Blower motor", price: 200, category: "HVAC", keywords: ["blower motor", "fan motor"] },
  { name: "Mini-split system", price: 900, category: "HVAC", keywords: ["mini-split", "minisplit", "ductless"] },
  { name: "Window AC unit", price: 250, category: "HVAC", keywords: ["window ac", "window unit"] },
  { name: "Portable AC", price: 350, category: "HVAC", keywords: ["portable ac"] },
  { name: "Whole-house humidifier", price: 180, category: "HVAC", keywords: ["whole house humidifier", "whole-house humid"] },
  { name: "Dehumidifier", price: 200, category: "HVAC", keywords: ["dehumidifier"] },
  { name: "Line set (25ft)", price: 65, category: "HVAC", keywords: ["line set", "refrigerant line"] },
  { name: "Condensate pump", price: 45, category: "HVAC", keywords: ["condensate pump", "condensate drain"] },
  { name: "UV air purifier", price: 120, category: "HVAC", keywords: ["uv air", "uv purif", "uv light hvac"] },
  // ── Hardware ──
  { name: "Lever handle set", price: 28, category: "Hardware", keywords: ["lever handle", "door lever"] },
  { name: "Latch/strike plate", price: 14, category: "Hardware", keywords: ["strike plate", "latch"] },
  { name: "Peephole", price: 12, category: "Hardware", keywords: ["peephole", "peep hole", "door viewer"] },
  { name: "Kick plate", price: 18, category: "Hardware", keywords: ["kick plate"] },
  { name: "Door knocker", price: 22, category: "Hardware", keywords: ["door knocker"] },
  { name: "Mail slot", price: 25, category: "Hardware", keywords: ["mail slot"] },
  { name: "Wood glue", price: 8, category: "Hardware", keywords: ["wood glue"] },
  { name: "Epoxy (2-part)", price: 12, category: "Hardware", keywords: ["epoxy adhesive", "2-part epoxy", "epoxy glue"] },
  { name: "Super glue", price: 5, category: "Hardware", keywords: ["super glue", "instant glue"] },
  { name: "Spray adhesive", price: 10, category: "Hardware", keywords: ["spray adhesive"] },
  { name: "Finish nails (pk)", price: 8, category: "Hardware", keywords: ["finish nail", "brad nail"] },
  { name: "Wood screws (1lb box)", price: 10, category: "Hardware", keywords: ["wood screw"] },
  { name: "Sheet metal screws (pk)", price: 8, category: "Hardware", keywords: ["sheet metal screw", "self tapping", "self-tap"] },
  { name: "Lag bolts (10pk)", price: 10, category: "Hardware", keywords: ["lag bolt", "lag screw"] },
  { name: "Carriage bolts (10pk)", price: 8, category: "Hardware", keywords: ["carriage bolt"] },
  { name: "Machine screws (pk)", price: 6, category: "Hardware", keywords: ["machine screw"] },
  { name: "Tapcon screws (pk)", price: 12, category: "Hardware", keywords: ["concrete screw", "tapcon"] },
  { name: "Toggle bolts (pk)", price: 8, category: "Hardware", keywords: ["toggle bolt"] },
  { name: "Wall anchors (pk)", price: 6, category: "Hardware", keywords: ["wall anchor", "drywall anchor"] },
  { name: "Washers (pk)", price: 4, category: "Hardware", keywords: ["flat washer", "washer assortment"] },
  { name: "Eye bolts (pk)", price: 6, category: "Hardware", keywords: ["eye bolt", "eye hook"] },
  { name: "Springs assortment", price: 8, category: "Hardware", keywords: ["spring assortment", "extension spring"] },
  { name: "S-hooks (pk)", price: 5, category: "Hardware", keywords: ["s-hook", "s hook"] },
  { name: "Snap hooks (pk)", price: 6, category: "Hardware", keywords: ["carabiner", "snap hook"] },
  { name: "Cable ties (100pk)", price: 8, category: "Hardware", keywords: ["cable tie", "zip tie"] },
  { name: "Nail plates (pk)", price: 6, category: "Hardware", keywords: ["nail plate", "protect plate"] },
  { name: "Metal strap tie", price: 5, category: "Hardware", keywords: ["strap tie", "metal strap"] },
  { name: "Shelf brackets (pair)", price: 10, category: "Hardware", keywords: ["shelf bracket"] },
  { name: "Shelf+brackets", price: 22, category: "Hardware", keywords: ["shelving", "shelf install"] },
  { name: "Wall hooks (pk)", price: 8, category: "Hardware", keywords: ["wall hook", "coat hook"] },
  { name: "Attic ladder", price: 200, category: "Hardware", keywords: ["attic ladder", "pull down stair", "pull-down stair"] },
  { name: "Closet rod+sockets", price: 12, category: "Hardware", keywords: ["closet rod"] },
  { name: "Closet organizer kit", price: 85, category: "Hardware", keywords: ["closet organizer", "closet system"] },
  { name: "Wire shelf (4ft)", price: 15, category: "Hardware", keywords: ["wire shelving"] },
  { name: "Garage wall organizer", price: 35, category: "Hardware", keywords: ["garage storage", "wall organizer"] },
  { name: "Ceiling hooks (pk)", price: 6, category: "Hardware", keywords: ["ceiling hook", "plant hook"] },
  { name: "Picture hanging kit", price: 8, category: "Hardware", keywords: ["picture hang", "picture hook"] },
  { name: "TV wall mount", price: 35, category: "Hardware", keywords: ["tv mount", "wall mount tv"] },
  // ── Insulation ──
  { name: "Expanding foam sealant", price: 8, category: "Insulation", keywords: ["foam sealant", "expanding foam", "great stuff"] },
  { name: "Fiberglass batt insulation (roll)", price: 40, category: "Insulation", keywords: ["batt insul", "fiberglass insul", "r-13", "r-19"] },
  { name: "Blown-in insulation (bag)", price: 18, category: "Insulation", keywords: ["blown", "cellulose", "blown-in"] },
  { name: "Foam board insulation (4x8)", price: 22, category: "Insulation", keywords: ["foam board", "rigid foam"] },
  { name: "Spray foam insulation kit", price: 450, category: "Insulation", keywords: ["spray foam"] },
  { name: "Pipe insulation (6ft)", price: 4, category: "Insulation", keywords: ["pipe insul", "pipe wrap"] },
  { name: "Duct insulation wrap", price: 22, category: "Insulation", keywords: ["duct insul", "duct wrap"] },
  { name: "Attic insulation (roll R-30)", price: 55, category: "Insulation", keywords: ["attic insul", "r-30"] },
  { name: "Radiant barrier (roll)", price: 65, category: "Insulation", keywords: ["radiant barrier"] },
  { name: "Foam weatherseal tape", price: 6, category: "Insulation", keywords: ["weatherseal", "foam tape"] },
  { name: "Vapor barrier (roll)", price: 30, category: "Insulation", keywords: ["vapor barrier", "visqueen", "plastic sheet"] },
  // ── Kitchen ──
  { name: "Laminate countertop (8ft)", price: 120, category: "Kitchen", keywords: ["laminate counter"] },
  { name: "Granite countertop (sq ft)", price: 55, category: "Kitchen", keywords: ["granite counter"] },
  { name: "Quartz countertop (sq ft)", price: 65, category: "Kitchen", keywords: ["quartz counter"] },
  { name: "Butcher block counter (6ft)", price: 180, category: "Kitchen", keywords: ["butcher block"] },
  { name: "Backsplash tile (sq ft)", price: 6, category: "Kitchen", keywords: ["backsplash", "back splash"] },
  { name: "Peel & stick backsplash", price: 35, category: "Kitchen", keywords: ["peel and stick backsplash", "peel stick back"] },
  { name: "Range hood", price: 180, category: "Kitchen", keywords: ["vent hood", "new range hood"] },
  { name: "Cabinet door (each)", price: 25, category: "Kitchen", keywords: ["cabinet door"] },
  { name: "Soft-close hinges (pk)", price: 18, category: "Kitchen", keywords: ["soft close", "soft-close hinge"] },
  { name: "Drawer slides (pair)", price: 18, category: "Kitchen", keywords: ["drawer slide", "drawer glide"] },
  { name: "Lazy Susan", price: 35, category: "Kitchen", keywords: ["lazy susan"] },
  { name: "Shelf liner (roll)", price: 10, category: "Kitchen", keywords: ["shelf liner"] },
  { name: "Undermount sink", price: 200, category: "Kitchen", keywords: ["undermount sink", "under mount sink"] },
  { name: "Pot filler faucet", price: 150, category: "Kitchen", keywords: ["pot filler"] },
  { name: "Ice maker line", price: 12, category: "Kitchen", keywords: ["ice maker line"] },
  { name: "Cabinet refinish kit", price: 55, category: "Kitchen", keywords: ["cabinet refinish", "refinish kit"] },
  // ── Masonry ──
  { name: "Pavers (sq ft)", price: 4, category: "Masonry", keywords: ["paver"] },
  { name: "Retaining wall block", price: 5, category: "Masonry", keywords: ["retaining wall"] },
  { name: "Mortar mix (60lb)", price: 8, category: "Masonry", keywords: ["mortar mix"] },
  { name: "Concrete block (8x8x16)", price: 3, category: "Masonry", keywords: ["concrete block", "cinder block", "cmu block"] },
  { name: "Brick (each)", price: 1, category: "Masonry", keywords: ["brick"] },
  { name: "Tuckpointing mortar", price: 12, category: "Masonry", keywords: ["tuckpoint", "tuck point", "repoint"] },
  { name: "Stone veneer (sq ft)", price: 12, category: "Masonry", keywords: ["stone veneer"] },
  // ── Paint ──
  { name: "Exterior paint (gal)", price: 75, category: "Paint", keywords: ["exterior paint"] },
  { name: "Wood stain (qt)", price: 18, category: "Paint", keywords: ["wood stain"] },
  { name: "Polyurethane (qt)", price: 22, category: "Paint", keywords: ["polyurethane", "clear coat"] },
  { name: "Deck stain (gal)", price: 45, category: "Paint", keywords: ["deck stain"] },
  { name: "Ceiling paint (gal)", price: 35, category: "Paint", keywords: ["ceiling paint"] },
  { name: "Cabinet paint (qt)", price: 28, category: "Paint", keywords: ["cabinet paint"] },
  { name: "Epoxy floor kit", price: 85, category: "Paint", keywords: ["epoxy paint", "garage floor paint", "epoxy floor"] },
  { name: "Concrete stain (gal)", price: 40, category: "Paint", keywords: ["concrete stain"] },
  { name: "Chalk paint (qt)", price: 24, category: "Paint", keywords: ["chalk paint"] },
  { name: "Paint stripper", price: 16, category: "Paint", keywords: ["paint stripper", "paint remover"] },
  { name: "Wood filler", price: 9, category: "Paint", keywords: ["wood filler", "wood putty"] },
  { name: "Sandpaper variety pk", price: 10, category: "Paint", keywords: ["sandpaper", "sanding paper"] },
  { name: "TSP cleaner", price: 8, category: "Paint", keywords: ["degreaser", "tsp cleaner"] },
  { name: "Wallpaper (roll)", price: 35, category: "Paint", keywords: ["wallpaper"] },
  { name: "Wallpaper remover", price: 12, category: "Paint", keywords: ["wallpaper remover", "strip wallpaper"] },
  // ── Plumbing ──
  { name: "Handheld shower", price: 35, category: "Plumbing", keywords: ["handheld shower", "hand held shower", "handheld"] },
  { name: "Shower valve", price: 55, category: "Plumbing", keywords: ["shower valve", "shower mixer"] },
  { name: "Shower door", price: 200, category: "Plumbing", keywords: ["shower door"] },
  { name: "Shower pan", price: 180, category: "Plumbing", keywords: ["shower pan", "shower base"] },
  { name: "Shower curtain+liner", price: 20, category: "Plumbing", keywords: ["shower curtain", "curtain liner"] },
  { name: "Bidet seat", price: 80, category: "Plumbing", keywords: ["bidet"] },
  { name: "Kitchen sink (SS)", price: 180, category: "Plumbing", keywords: ["kitchen sink"] },
  { name: "Bathroom sink", price: 75, category: "Plumbing", keywords: ["bathroom sink", "vanity sink", "lav sink"] },
  { name: "Pedestal sink", price: 140, category: "Plumbing", keywords: ["pedestal sink", "pedestal"] },
  { name: "Utility sink", price: 85, category: "Plumbing", keywords: ["utility sink", "laundry sink"] },
  { name: "Drain snake/auger", price: 15, category: "Plumbing", keywords: ["drain clean", "auger", "snake", "clog"] },
  { name: "Pipe joint compound", price: 6, category: "Plumbing", keywords: ["pipe dope", "joint compound"] },
  { name: "Pipe clamp", price: 5, category: "Plumbing", keywords: ["pipe clamp"] },
  { name: "SharkBite fitting", price: 10, category: "Plumbing", keywords: ["sharkbite", "shark bite", "push fit"] },
  { name: "Expansion tank", price: 45, category: "Plumbing", keywords: ["expansion tank"] },
  { name: "Hose bib", price: 18, category: "Plumbing", keywords: ["hose bib", "spigot", "outdoor faucet"] },
  { name: "Tankless water heater", price: 800, category: "Plumbing", keywords: ["tankless"] },
  { name: "Anode rod", price: 25, category: "Plumbing", keywords: ["anode rod"] },
  { name: "Sump pump", price: 150, category: "Plumbing", keywords: ["sump pump"] },
  { name: "Ejector pump", price: 250, category: "Plumbing", keywords: ["ejector pump"] },
  { name: "PEX pipe (10ft)", price: 12, category: "Plumbing", keywords: ["pex pipe", "pex tubing"] },
  { name: "Copper pipe (10ft)", price: 28, category: "Plumbing", keywords: ["copper pipe"] },
  { name: "PVC pipe (10ft)", price: 8, category: "Plumbing", keywords: ["pvc pipe"] },
  { name: "ABS pipe (10ft)", price: 10, category: "Plumbing", keywords: ["abs pipe"] },
  { name: "CPVC pipe (10ft)", price: 10, category: "Plumbing", keywords: ["cpvc"] },
  { name: "Ball valve", price: 12, category: "Plumbing", keywords: ["ball valve"] },
  { name: "Check valve", price: 18, category: "Plumbing", keywords: ["check valve"] },
  { name: "Pressure regulator", price: 55, category: "Plumbing", keywords: ["pressure regulator", "prv valve"] },
  { name: "Backflow preventer", price: 45, category: "Plumbing", keywords: ["backflow"] },
  { name: "Water filter system", price: 65, category: "Plumbing", keywords: ["water filter", "whole house filter"] },
  { name: "Water softener", price: 400, category: "Plumbing", keywords: ["water softener"] },
  { name: "Cleanout plug", price: 8, category: "Plumbing", keywords: ["cleanout", "clean out", "sewer"] },
  { name: "Septic treatment", price: 20, category: "Plumbing", keywords: ["septic"] },
  { name: "Water line connector kit", price: 12, category: "Plumbing", keywords: ["water line connect"] },
  // ── Roofing ──
  { name: "Butyl flashing tape", price: 18, category: "Roofing", keywords: ["butyl tape", "flashing tape"] },
  { name: "Architectural shingles (bundle)", price: 40, category: "Roofing", keywords: ["architectural shingle", "dimensional shingle"] },
  { name: "Metal roofing panel (3x12)", price: 35, category: "Roofing", keywords: ["metal roof", "standing seam"] },
  { name: "EPDM membrane (sq ft)", price: 3, category: "Roofing", keywords: ["epdm", "rubber roof", "membrane roof"] },
  { name: "Roof felt (roll)", price: 25, category: "Roofing", keywords: ["roof felt", "tar paper"] },
  { name: "Ice & water shield (roll)", price: 55, category: "Roofing", keywords: ["ice and water shield", "ice barrier"] },
  { name: "Synthetic underlayment (roll)", price: 65, category: "Roofing", keywords: ["synthetic underlayment"] },
  { name: "Step flashing (pk)", price: 18, category: "Roofing", keywords: ["step flashing"] },
  { name: "Ridge vent (4ft)", price: 18, category: "Roofing", keywords: ["ridge vent"] },
  { name: "Roof turbine vent", price: 35, category: "Roofing", keywords: ["turbine vent", "roof turbine"] },
  { name: "Drip edge (10ft)", price: 10, category: "Roofing", keywords: ["drip edge"] },
  { name: "Soffit panel (12ft)", price: 22, category: "Roofing", keywords: ["soffit"] },
  { name: "Fascia board (12ft)", price: 25, category: "Roofing", keywords: ["fascia"] },
  { name: "Roofing nails (5lb)", price: 12, category: "Roofing", keywords: ["roofing nail", "coil nail"] },
  { name: "Skylight flashing kit", price: 55, category: "Roofing", keywords: ["skylight flashing"] },
  { name: "Gutter screws (pk)", price: 8, category: "Roofing", keywords: ["gutter screw", "gutter spike"] },
  // ── Safety ──
  { name: "Radon detector", price: 30, category: "Safety", keywords: ["radon"] },
  { name: "Security camera", price: 60, category: "Safety", keywords: ["security camera", "surveillance camera"] },
  { name: "Motion detector", price: 25, category: "Safety", keywords: ["motion detector", "motion detection"] },
  { name: "Battery backup (UPS)", price: 65, category: "Safety", keywords: ["battery backup", "ups backup", "uninterruptible"] },
  { name: "Outlet tester", price: 10, category: "Safety", keywords: ["outlet tester", "gfi tester", "receptacle tester"] },
  { name: "Child safety outlet covers (12pk)", price: 8, category: "Safety", keywords: ["child proof", "child safe", "tamper resist", "childproof"] },
  // ── Trim ──
  { name: "Window casing (7ft)", price: 12, category: "Trim", keywords: ["window trim", "window casing"] },
  { name: "Baseboard (8ft)", price: 10, category: "Trim", keywords: ["baseboard", "base board"] },
  { name: "Crown molding (8ft)", price: 12, category: "Trim", keywords: ["crown mold"] },
  { name: "Chair rail (8ft)", price: 10, category: "Trim", keywords: ["chair rail"] },
  { name: "Casing (7ft)", price: 8, category: "Trim", keywords: ["casing", "door trim", "window casing"] },
  { name: "Quarter round (8ft)", price: 5, category: "Trim", keywords: ["quarter round"] },
  { name: "Wainscoting panel (4x8)", price: 35, category: "Trim", keywords: ["wainscot"] },
  { name: "Beadboard panel", price: 28, category: "Trim", keywords: ["beadboard"] },
  { name: "Picture rail (8ft)", price: 8, category: "Trim", keywords: ["picture rail", "picture mold"] },
  { name: "Corner rosette", price: 5, category: "Trim", keywords: ["rosette"] },
  { name: "Plinth block", price: 6, category: "Trim", keywords: ["plinth block"] },
  { name: "Handrail (8ft)", price: 25, category: "Trim", keywords: ["stair railing", "handrail", "banister"] },
  { name: "Baluster (each)", price: 8, category: "Trim", keywords: ["baluster", "spindle"] },
  { name: "Newel post", price: 45, category: "Trim", keywords: ["newel post"] },
  // ── Windows ──
  { name: "Vinyl window", price: 250, category: "Windows", keywords: ["window replace", "replace window", "new window"] },
  { name: "Double-hung window", price: 280, category: "Windows", keywords: ["double hung", "double-hung"] },
  { name: "Casement window", price: 320, category: "Windows", keywords: ["casement"] },
  { name: "Egress window", price: 350, category: "Windows", keywords: ["egress", "basement window"] },
  { name: "Skylight", price: 400, category: "Windows", keywords: ["skylight"] },
  { name: "Window well", price: 65, category: "Windows", keywords: ["window well"] },
  { name: "Storm window", price: 85, category: "Windows", keywords: ["storm window"] },
  { name: "Faux wood blind", price: 35, category: "Windows", keywords: ["faux wood", "wood blind"] },
  { name: "Cellular shade", price: 45, category: "Windows", keywords: ["cellular shade", "honeycomb"] },
  { name: "Roller shade", price: 28, category: "Windows", keywords: ["roller shade"] },
  { name: "Curtain rod", price: 18, category: "Windows", keywords: ["curtain rod"] },
  { name: "Curtain panel", price: 25, category: "Windows", keywords: ["curtain panel", "drape"] },
  { name: "Window film", price: 14, category: "Windows", keywords: ["window film", "window tint", "privacy film"] },
  { name: "Window caulk", price: 9, category: "Windows", keywords: ["window caulk", "window seal"] },
  { name: "Glass pane", price: 40, category: "Windows", keywords: ["glass pane", "broken glass", "cracked glass"] },
  { name: "Glazing compound", price: 8, category: "Windows", keywords: ["glazing compound", "glazing point"] },
  { name: "Window lock", price: 8, category: "Windows", keywords: ["window lock", "sash lock"] },
];

// Lookup function — find best matching material from database
export function findMaterial(text: string): MaterialItem | null {
  const s = text.toLowerCase();
  let best: MaterialItem | null = null;
  let bestScore = 0;

  for (const item of MATERIALS_DB) {
    let score = 0;
    for (const kw of item.keywords) {
      if (s.includes(kw)) {
        score += kw.length; // longer keyword matches = better match
      }
    }
    if (score > bestScore) {
      bestScore = score;
      best = item;
    }
  }

  return bestScore > 3 ? best : null; // minimum match threshold
}

// Get all materials in a category
export function getMaterialsByCategory(category: string): MaterialItem[] {
  return MATERIALS_DB.filter((m) => m.category === category);
}

// Search materials
export function searchMaterials(query: string): MaterialItem[] {
  const q = query.toLowerCase();
  return MATERIALS_DB.filter((m) =>
    m.name.toLowerCase().includes(q) ||
    m.keywords.some((kw) => kw.includes(q))
  );
}
